### ISSUE TITLE
password based ssh is disabled by default on CoreOS

### ISSUE THREAD

**Issue by AdrianKoshka** [cockpit-project/cockpit-container#16]
In my sshd config I had the line `PasswordAuthentication no`, because I use keys. I found out though, if I had this option enabled, logging into cockpit doesn't work, I simply get the error: 

`The server refused to authenticate 'alc' using password authentication, and no other supportedauthentication methods are available.`

This seems like a poor design choice, it punishes you for trying to harden your system.

**Comment by martinpitt** [comment]
You can add your ssh key in the "Authentication" menu entry in the user menu at the top right, then it will use key based auth. Does that not work for you?

**Comment by AdrianKoshka** [comment]
I don't see how that'd work. The only way to authenticate you can initially go to the login page for cockpit is a username/password, after that you can use an SSH key. I've "solved" the issue simply by installing cockpit on my main machine then just adding the atomic host system as a connection in the dashboard.

**Comment by gtherond** [comment]
I second this issue, it will become more and more prevalent with FCOS/RHCOS/Atomic hosts that don't let you use password for connection.

But the issue here is that there are no elegant way for a webBrowser to securely use your private key.

Additionally, as this container is run as a privileged container, you can't trust it and it could actually harm your machine.

I really think that cockpit within *COS Distribution should behave otherwise.

**Comment by lukasmrtvy** [comment]
Is cockpit even supported in Fedora CoreOS ?

**Comment by martinpitt** [comment]
>Is cockpit even supported in Fedora CoreOS ?

Yes, we do test it on CoreOS, and have spent quite some time on making it work there  (see [Running](https://cockpit-project.org/running.html#coreos) page).

There is no easy way out of that -- if you want to directly log into Cockpit on FCOS and use the cockpit/ws container, you only have these options:

 - reconfigure SSH and use password-based login
 - be part of an Identity Management domain, and have a kerberos ticket (https://cockpit-project.org/guide/latest/sso.html)
 - install the cockpit-ws package into the OSTree instead of using the cockpit/ws container.

But I do agree that we should point this out in the documentation.

**Comment by gtherond** [comment]
Honestly, as the cockpit-ws container run as a privileged one, I do agree that adding a package to your initial RPM-OSTree layer within FCOS isn't that of an issue here.

The SSO part is also another elegant way to do it.

Thanks a lot @martinpitt.

**Comment by martinpitt** [comment]
Reopening to update the documentation.

**Comment by martinpitt** [comment]
Sent doc update in https://github.com/cockpit-project/cockpit/pull/14209

**Comment by martinpitt** [comment]
Reopening, as it still didn't make its way into the cockpit-container repo and the dockerhub page.

**Comment by arctic-alpaca** [comment]
The [documentation on the cockpit-project website](https://cockpit-project.org/running.html#coreos) regarding Fedora CoreOS is not updated with this information.

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit-project.github.io/pull/420 to update the web site.
